// <auto-generated />
namespace APP.StoreManager.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v003));
        
        string IMigrationMetadata.Id
        {
            get { return "201512031618165_v-003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
