// <auto-generated />
namespace APP.StoreManager.Infra.CrossCutting.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v002));
        
        string IMigrationMetadata.Id
        {
            get { return "201511271935245_v-002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
